### ISSUE TITLE
why examples doas not compile ?

### ISSUE THREAD

**Issue by radoslawtwardy** [jrudolph/json-lenses#1]
When i try;
`val authorNames = json.extract {String} (allAuthors)`
i get:

```
 error: could not find implicit value for evidence parameter of type cc.spray.json.lenses.package.Reader{String}
```

When i try:
`val newJson1 = json.update(allAuthors ! set {String} ("John Doe"))`
i get:

```
error: Cannot find JsonWriter or JsonFormat type class for String
```

// i must replaced [ with { because with [ i cant add properly msg

**Comment by Cadovvl** [comment]
adding import 
`import DefaultJsonProtocol._`
have helped me with the same problem
