### ISSUE TITLE
scala & spray version upgrade?

### ISSUE THREAD

**Issue by mayacr86** [jrudolph/json-lenses#17]
Hi! Just wondering, any plans to build an upgraded version of the lib? (to use most recent versions of scala and spray)

**Comment by jrudolph** [comment]
It seems the latest version should still be binary compatible. Did you encounter any incompatibilities?

**Comment by mayacr86** [comment]
Sorry, I posted the question before looking at spray-json latest version. And no, I have no problems at all :) [silently walks away] lol
