### ISSUE TITLE
Can't find copyright notice

### ISSUE THREAD

**Issue by akauppi** [jrudolph/json-lenses#25]
The Apache 2.0 license requires the author to place a copyright notice in the source. I did not find such.

```
 "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).
```

This makes it more difficult to attribute your project correctly. I would suggest to check some other Apache 2.0 project and see how they claim copyright. To me, a notion anywhere within say `README.md` (either beginning or the very end, where license is mentioned) would be sufficient.

**Addendum:**

In fact, the README.md currently says:

```
spray-json is licensed under APL 2.0.
```

Copy-paste error. Should say `json-lenses`.

**Comment by jrudolph** [comment]
Thanks, good point, I will fix this in the next version.
